"""Model registry — GO/NO-GO gated registration for AI models.

s3-ai-research-pipeline (wave2, T-s3-03): registry + paper → live promotion
gate. ``register`` refuses any model whose validation report did not pass
``validation_gate`` (decision != "GO") — fail-closed. P0 strongest-gaps also
requires a fee×slip cost grid (and rejects zero-cost-only GO narratives).
Models live as JSON entries under ``registry_dir``; ``promote`` moves a paper
model to live only if the paper registration exists and is intact.
"""

from __future__ import annotations

import json
import logging
import uuid
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from quantflow.strategy.validation.cost_fidelity import (
    CostFidelityError,
    assert_promotion_cost_ready,
)

logger = logging.getLogger(__name__)

#: Registry status values (ordered lifecycle).
STATUS_REJECTED = "rejected"
STATUS_PAPER = "paper"
STATUS_LIVE = "live"
VALID_STATUSES = (STATUS_REJECTED, STATUS_PAPER, STATUS_LIVE)

#: Statuses that may be promoted to live.
PROMOTABLE = (STATUS_PAPER,)


class ModelRegistryError(RuntimeError):
    """Raised on registry violations (duplicate id, bad status, gate fail)."""


class ModelRegistry:
    """Persistent model registry with fail-closed gates.

    Usage::

        reg = ModelRegistry("data/models")
        reg.register(model_id="m1", model_cls="RandomForestClassifier",
                     features_hash="abc", validation_report={"decision": "GO", ...})
        reg.promote_to_live("m1")   # paper → live
    """

    def __init__(self, registry_dir: str | Path) -> None:
        self._dir = Path(registry_dir)
        self._dir.mkdir(parents=True, exist_ok=True)

    def _path(self, model_id: str) -> Path:
        if not model_id or "/" in model_id or "\\" in model_id or ".." in model_id:
            raise ModelRegistryError(f"Invalid model_id: {model_id!r}")
        return self._dir / f"{model_id}.json"

    @staticmethod
    def new_id() -> str:
        return f"model-{uuid.uuid4().hex[:12]}"

    def register(
        self,
        model_id: str,
        model_cls: str,
        features_hash: str,
        validation_report: dict[str, Any],
    ) -> dict[str, Any]:
        """Register a model only when its validation gate passed (fail-closed).

        Args:
            model_id: Stable id (auto-generated by callers when unknown).
            model_cls: Class name of the model.
            features_hash: Hash of the feature schema used at training.
            validation_report: Output of ``validation_gate`` (or an
                equivalent dict with ``decision``).

        Returns:
            The persisted registry entry.

        Raises:
            ModelRegistryError: when ``decision != "GO"`` (refused) or the
                id already exists.
        """
        decision = str(validation_report.get("decision", "NO-GO"))
        if decision != "GO":
            reason = str(validation_report.get("reason", "gate did not pass"))
            logger.warning("Registry refuses %s: %s (fail-closed)", model_id, reason)
            entry = {
                "model_id": model_id,
                "model_cls": model_cls,
                "features_hash": features_hash,
                "status": STATUS_REJECTED,
                "decision": decision,
                "reason": reason,
                "registered_at": self._now(),
            }
            self._write(entry)
            return entry

        # P0 T001: GO is necessary but not sufficient — cost grid required.
        try:
            assert_promotion_cost_ready(validation_report)
        except CostFidelityError as exc:
            reason = f"cost fidelity gate: {exc}"
            logger.warning("Registry refuses %s: %s (fail-closed)", model_id, reason)
            entry = {
                "model_id": model_id,
                "model_cls": model_cls,
                "features_hash": features_hash,
                "status": STATUS_REJECTED,
                "decision": "NO-GO",
                "reason": reason,
                "registered_at": self._now(),
            }
            self._write(entry)
            return entry

        path = self._path(model_id)
        if path.exists():
            raise ModelRegistryError(f"Model {model_id!r} already registered")

        entry = {
            "model_id": model_id,
            "model_cls": model_cls,
            "features_hash": features_hash,
            "status": STATUS_PAPER,
            "decision": "GO",
            "reason": "validation gate + cost fidelity passed",
            "registered_at": self._now(),
            "validation": _summarize_validation(validation_report),  # type: ignore[dict-item]
        }
        self._write(entry)
        logger.info("Registered model %s (paper)", model_id)
        return entry

    def promote_to_live(self, model_id: str) -> dict[str, Any]:
        """Promote a paper model to live (requires intact paper registration)."""
        entry = self.get(model_id)
        if entry is None:
            raise ModelRegistryError(f"Model {model_id!r} not found")
        if entry["status"] not in PROMOTABLE:
            raise ModelRegistryError(
                f"Model {model_id!r} status={entry['status']} is not promotable "
                f"(require one of {PROMOTABLE})"
            )
        entry["status"] = STATUS_LIVE
        entry["promoted_at"] = self._now()
        self._write(entry)
        logger.info("Promoted model %s to live", model_id)
        return entry

    def get(self, model_id: str) -> dict[str, Any] | None:
        path = self._path(model_id)
        if not path.exists():
            return None
        loaded: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))
        return loaded

    def list_models(self) -> list[dict[str, Any]]:
        entries: list[dict[str, Any]] = []
        for path in sorted(self._dir.glob("*.json")):
            entries.append(json.loads(path.read_text(encoding="utf-8")))
        return entries

    def _write(self, entry: dict[str, Any]) -> None:
        path = self._path(entry["model_id"])
        path.write_text(json.dumps(entry, ensure_ascii=False, indent=2), encoding="utf-8")

    @staticmethod
    def _now() -> str:
        return datetime.now(UTC).isoformat()


def _summarize_validation(report: dict[str, Any]) -> dict[str, Any]:
    """Keep a compact, JSON-safe subset of the validation report."""
    keep: dict[str, Any] = {}
    for key in ("decision", "reason"):
        if key in report:
            keep[key] = report[key]
    checks = report.get("checks")
    if isinstance(checks, dict):
        keep["checks"] = {
            k: {
                ck: v
                for ck, v in (v.items() if isinstance(v, dict) else [])
                if ck in ("passed", "dsr", "pbo", "oos_efficiency")
            }
            for k, v in checks.items()
            if isinstance(v, dict)
        }
    return keep
